# Generated by Django 3.0.5 on 2022-12-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
