# Generated by Django 3.0.5 on 2022-12-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Signup',
        ),
    ]
